Repository jheddings/pingdat, pull requests merged in 2024-05, with the labels that each got.

#207 Update dependency pre-commit to ^3.7.1
  poetry.lock
  pyproject.toml
Labels: dependencies, renovate, dep:python, dep:ci

#212 Use real black package.
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#213 Update dependency requests to ^2.32.0
  poetry.lock
  pyproject.toml
Labels: dependencies, renovate, dep:python

#214 Improve error handling for network issues.
  .github/workflows/unit-tests.yaml
  .pre-commit-config.yaml
  Makefile
  etc/pingdat.service
  poetry.lock
  pyproject.toml
  src/pingdat/__init__.py
  src/pingdat/__main__.py
  tests/test_localhost.py
  tests/test_targets.py
Labels: bug, enhancement

#216 Update jheddings/pingdat Docker tag to v1.5.0
  etc/docker-compose.yaml
Labels: dependencies, renovate, dep:docker
